In [1]:
import pandas as pd
import openpyxl

In [2]:
path = r"H:\python\python-tecTI\dados\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

In [12]:
tabela_bruta = pd.read_excel(path, header=None)

In [13]:
tabela_bruta

,0,1,2,3,4,5,6,7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Censo Demográfico 2022: População e Domicílios...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
3,NaN,RO,11,00015,Alta Floresta D'Oeste,24392,24392,21494
4,NaN,RO,11,00023,Ariquemes,90353,90353,96833
...,...,...,...,...,...,...,...,...
5572,NaN,DF,53,00108,Brasília,2570160,2572159,2817381
5573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5574,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5576,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
tabela_censo = tabela_bruta.iloc[3:5572, [1,4,5,7]].copy()

In [25]:
tabela_censo

      UF              Municipio  pop10  pop22   dif
3     RO  Alta Floresta D'Oeste  24392  21494 -2898
4     RO              Ariquemes  90353  96833  6480
5     RO                 Cabixi   6313   5351  -962
6     RO                 Cacoal  78574  86887  8313
7     RO             Cerejeiras  17029  15890 -1139
...   ..                    ...    ...    ...   ...
5567  GO                 Varjão   3659   3716    57
5568  GO             Vianópolis  12548  14956  2408
5569  GO         Vicentinópolis   7371   8768  1397
5570  GO               Vila Boa   4735   4215  -520
5571  GO          Vila Propício   5145   5815   670

[5569 rows x 5 columns]

In [21]:
tabela_censo.columns = [
    "UF",
    "Municipio",
    "pop10",
    "pop22"
]

In [23]:
tabela_censo["pop10"] = pd.to_numeric(tabela_censo["pop10"], errors="coerce")
tabela_censo["pop22"] = pd.to_numeric(tabela_censo["pop22"], errors="coerce")

In [24]:
tabela_censo["dif"] = tabela_censo["pop22"] - tabela_censo["pop10"]

In [30]:
pop_estado = (
    tabela_censo.groupby(["UF"], as_index=False)
      .agg(
          pop_2010=("pop10", "sum"),
          pop_2022=("pop22", "sum"),
          dif_estado = ("dif", "sum")
          
      )
)

In [32]:
pop_estado = pop_estado.sort_values(by="dif_estado", ascending=False, ignore_index=True)

In [33]:
pop_estado

    UF  pop_2010  pop_2022  dif_estado
0   SP  41262199  44411238     3149039
1   SC   6248436   7610361     1361925
2   GO   6003788   7056495     1052707
3   PR  10444526  11444380      999854
4   MG  19597330  20539989      942659
5   MT   3035122   3658649      623527
6   PA   7581051   8120131      539080
7   AM   3483985   3941613      457628
8   CE   8452381   8794957      342576
9   ES   3514952   3833712      318760
10  MS   2449024   2757013      307989
11  PE   8796448   9058931      262483
12  PB   3766528   3974687      208159
13  MA   6574789   6776699      201910
14  RS  10693929  10882965      189036
15  RR    450479    636707      186228
16  PI   3118360   3271199      152839
17  SE   2068017   2210004      141987
18  RN   3168027   3302729      134702
19  TO   1383445   1511460      128015
20  BA  14016906  14141626      124720
21  AC    733559    830018       96459
22  RJ  15989929  16055174       65245
23  AP    669526    733759       64233
24  RO   1562409   1581196       18787
25  AL   3120494   3127683        7189

In [40]:
pop_municipio = tabela_censo.sort_values(by="dif", ascending=False, ignore_index=True)

In [42]:
pop_municipio.to_csv(r"H:\python\python-tecTI\dados\Dados_municipio.csv")

In [43]:
pop_estado.to_csv(r"H:\python\python-tecTI\dados\Dados_estado.csv")